// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBULMaWY0EVdgmxDFLAutIBTua_IPOiAFc',
    appId: '1:910709124426:web:513d6e33d075f65fdc25b3',
    messagingSenderId: '910709124426',
    projectId: 'gemini-code-assitance-6c7b1',
    authDomain: 'gemini-code-assitance-6c7b1.firebaseapp.com',
    storageBucket: 'gemini-code-assitance-6c7b1.firebasestorage.app',
    measurementId: 'G-7YQYYYTLGZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJqwRKDNAM7IRhwTM0AZW-8-3i3R1mqRA',
    appId: '1:910709124426:android:f225e72abfda8adddc25b3',
    messagingSenderId: '910709124426',
    projectId: 'gemini-code-assitance-6c7b1',
    storageBucket: 'gemini-code-assitance-6c7b1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6emk57DLkZ_rOCN2NBgV_5-6If-AC0cg',
    appId: '1:910709124426:ios:aaf11dc7d4a40c53dc25b3',
    messagingSenderId: '910709124426',
    projectId: 'gemini-code-assitance-6c7b1',
    storageBucket: 'gemini-code-assitance-6c7b1.firebasestorage.app',
    iosBundleId: 'com.example.smartPot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6emk57DLkZ_rOCN2NBgV_5-6If-AC0cg',
    appId: '1:910709124426:ios:aaf11dc7d4a40c53dc25b3',
    messagingSenderId: '910709124426',
    projectId: 'gemini-code-assitance-6c7b1',
    storageBucket: 'gemini-code-assitance-6c7b1.firebasestorage.app',
    iosBundleId: 'com.example.smartPot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyASMBC0_zVvdubOFD0lC4Zm2TBIelEPhCk',
    appId: '1:910709124426:web:9c93bd464fd80053dc25b3',
    messagingSenderId: '910709124426',
    projectId: 'gemini-code-assitance-6c7b1',
    authDomain: 'gemini-code-assitance-6c7b1.firebaseapp.com',
    storageBucket: 'gemini-code-assitance-6c7b1.firebasestorage.app',
    measurementId: 'G-M8SW53517B',
  );
}
